#include "minunit.h"
#include <lcthw/list_algos.h>
#include <assert.h>
#include <string.h>
#include <time.h>
#include <stdio.h>

char *values[] = {"XXXX", "1234", "abcd", "xjvef", "NDSS"};
#define NUM_VALUES 5

char *random_strings[100] = {
    "u5A", "9YK", "b74", "O1H", "Zj8", "dSj", "2kI", "4tD", "LkT", "7Pv",
    "C3m", "f9R", "xL6", "QpO", "a2G", "eN5", "k1J", "vT8", "Hs7", "yFt",
    "Iu9", "3pE", "R6c", "Tb5", "oJx", "W4q", "zS1", "Vg9", "Yk3", "lD6",
    "5nM", "B7h", "Mv4", "6eZ", "G2s", "jP8", "1aK", "Dc7", "Tt3", "qW6",
    "K8l", "5Oc", "9rA", "F4v", "yH3", "Pd7", "3sT", "N6b", "Gq2", "Uz5",
    "o9W", "x4K", "lF7", "Y6p", "jvT", "Q3c", "aW5", "n2B", "Iz8", "Vr4",
    "w6U", "Eo3", "z5j", "6Ic", "S8b", "k2L", "0pR", "h9G", "Tl5", "dQ7",
    "b4M", "G7x", "cV2", "Jf6", "u3N", "9Qw", "X6a", "Pb3", "4sL", "v8D",
    "R1n", "tS5", "Dq9", "zLc", "7wX", "K4e", "x2G", "U8r", "I3t", "oH6",
    "h5M", "L7v", "yC4", "Wj2", "p8D", "Nf6", "2aT", "T6n", "b9R", "S3q"
};  // generated by GPT-3.5-Turbo
#define NUM_VALUES_RANDOM 100

List *create_words()
{
    int i = 0;
    List *words = List_create();

    for(i = 0; i < NUM_VALUES; i++) {
        List_push(words, values[i]);
    }

    return words;
}

List *create_words_100()
{
    int i = 0;
    List *words = List_create();

    for(i = 0; i < NUM_VALUES_RANDOM; i++) {
        List_push(words, random_strings[i]);
    }

    return words;
}

List *create_words_500()
{
    int i = 0;
    List *words = List_create();

    for(i = 0; i < NUM_VALUES_RANDOM * 5; i++) {
        List_push(words, random_strings[i%NUM_VALUES_RANDOM]);
    }

    return words;
}

int is_sorted(List *words)
{
    LIST_FOREACH(words, first, next, cur) {
        if(cur->next && strcmp(cur->value, cur->next->value) > 0) {
            debug("%s %s", (char *)cur->value, (char *)cur->next->value);
            return 0;
        }
    }

    return 1;
}

char *test_bubble_sort()
{
    List *words = create_words();

    // should work on a list that needs sorting
    int rc = List_bubble_sort(words, (List_compare)strcmp);
    mu_assert(rc == 0, "Bubble sort failed.");
    mu_assert(is_sorted(words), "Words are not sorted after bubble sort.");

    // should work on an already sorted list
    rc = List_bubble_sort(words, (List_compare)strcmp);
    mu_assert(rc == 0, "Bubble sort of already sorted failed.");
    mu_assert(is_sorted(words), "Words should be sort if already bubble sorted.");

    List_destroy(words);

    // should work on an empty list
    words = List_create(words);
    rc = List_bubble_sort(words, (List_compare)strcmp);
    mu_assert(rc == 0, "Bubble sort failed on empty list.");
    mu_assert(is_sorted(words), "Words should be sorted if empty.");

    List_destroy(words);

    return NULL;
}

char *test_merge_sort()
{
    List *words = create_words();

    // should work on a list that needs sorting
    List *res = List_merge_sort(words, (List_compare)strcmp);
    mu_assert(is_sorted(res), "Words are not sorted after merge sort.");

    List *res2 = List_merge_sort(res, (List_compare)strcmp);
    mu_assert(is_sorted(res), "Should still be sorted after merge sort.");
    List_destroy(res2);
    List_destroy(res);

    List_destroy(words);
    return NULL;
}


char *test_bubble_sort_5()
{

    clock_t start, end;
    double cpu_time_used;
    start = clock();    // counter start

    for(int i = 0; i < 1000000; i++) {
         List *words = create_words();
         int rc = List_bubble_sort(words, (List_compare)strcmp);
         List_destroy(words);
    }

    end = clock();      // counter end
    cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC; // 计算执行时间
    printf("bubble sort time: %f seconds\n", cpu_time_used);
    return NULL;
}

char *test_merge_sort_5()
{

    clock_t start, end;
    double cpu_time_used;
    start = clock();    // counter start

    for(int i = 0; i < 1000000; i++) {
         List *words = create_words();
         List *res = List_merge_sort(words, (List_compare)strcmp);
         List_destroy(res);
         List_destroy(words);
    }

    end = clock();      // counter end
    cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC; // 计算执行时间
    printf("merge sort time: %f seconds\n", cpu_time_used);
    return NULL;
}

char *test_bubble_sort_100()
{

    clock_t start, end;
    double cpu_time_used;
    start = clock();    // counter start

    for(int i = 0; i < 100000; i++) {
         List *words = create_words_100();
         int rc = List_bubble_sort(words, (List_compare)strcmp);
         List_destroy(words);
    }

    end = clock();      // counter end
    cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC; // 计算执行时间
    printf("100-len: bubble sort time: %f seconds\n", cpu_time_used);
    return NULL;
}

char *test_merge_sort_100()
{

    clock_t start, end;
    double cpu_time_used;
    start = clock();    // counter start

    for(int i = 0; i < 100000; i++) {
         List *words = create_words_100();
         List *res = List_merge_sort(words, (List_compare)strcmp);
         List_destroy(res);
         List_destroy(words);
    }

    end = clock();      // counter end
    cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC; // 计算执行时间
    printf("100-len: merge sort time: %f seconds\n", cpu_time_used);
    return NULL;
}

char *test_bubble_sort_500()
{

    clock_t start, end;
    double cpu_time_used;
    start = clock();    // counter start

    for(int i = 0; i < 100000; i++) {
         List *words = create_words_500();
         int rc = List_bubble_sort(words, (List_compare)strcmp);
         List_destroy(words);
    }

    end = clock();      // counter end
    cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC; // 计算执行时间
    printf("500-len: bubble sort time: %f seconds\n", cpu_time_used);
    return NULL;
}

char *test_merge_sort_500()
{

    clock_t start, end;
    double cpu_time_used;
    start = clock();    // counter start

    for(int i = 0; i < 100000; i++) {
         List *words = create_words_500();
         List *res = List_merge_sort(words, (List_compare)strcmp);
         List_destroy(res);
         List_destroy(words);
    }

    end = clock();      // counter end
    cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC; // 计算执行时间
    printf("500-len: merge sort time: %f seconds\n", cpu_time_used);
    return NULL;
}


char *all_tests()
{
    mu_suite_start();

    mu_run_test(test_bubble_sort);
    mu_run_test(test_merge_sort);
    mu_run_test(test_bubble_sort_5);
    mu_run_test(test_merge_sort_5);
    // mu_run_test(test_bubble_sort_100);
    // mu_run_test(test_merge_sort_100);
    // mu_run_test(test_bubble_sort_500);
    // mu_run_test(test_merge_sort_500);

    return NULL;
}

RUN_TESTS(all_tests);