/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module lfsr(clk, rst_n, din, dout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  input clk;
  input [7:0] din;
  output [7:0] dout;
  input rst_n;
  MUX2_X1 _44_ (
    .A(_16_),
    .B(_25_),
    .S(_35_),
    .Z(_08_)
  );
  MUX2_X1 _45_ (
    .A(_17_),
    .B(_26_),
    .S(_35_),
    .Z(_09_)
  );
  MUX2_X1 _46_ (
    .A(_18_),
    .B(_27_),
    .S(_35_),
    .Z(_10_)
  );
  MUX2_X1 _47_ (
    .A(_19_),
    .B(_28_),
    .S(_35_),
    .Z(_11_)
  );
  MUX2_X1 _48_ (
    .A(_20_),
    .B(_29_),
    .S(_35_),
    .Z(_12_)
  );
  MUX2_X1 _49_ (
    .A(_21_),
    .B(_30_),
    .S(_35_),
    .Z(_13_)
  );
  MUX2_X1 _50_ (
    .A(_22_),
    .B(_31_),
    .S(_35_),
    .Z(_14_)
  );
  XOR2_X2 _51_ (
    .A(_28_),
    .B(_24_),
    .Z(_32_)
  );
  XNOR2_X2 _52_ (
    .A(_26_),
    .B(_27_),
    .ZN(_33_)
  );
  XNOR2_X1 _53_ (
    .A(_32_),
    .B(_33_),
    .ZN(_34_)
  );
  MUX2_X2 _54_ (
    .A(_23_),
    .B(_34_),
    .S(_35_),
    .Z(_15_)
  );
  BUF_X1 _55_ (
    .A(din[0]),
    .Z(_16_)
  );
  BUF_X1 _56_ (
    .A(dout[1]),
    .Z(_25_)
  );
  BUF_X1 _57_ (
    .A(rst_n),
    .Z(_35_)
  );
  BUF_X1 _58_ (
    .A(_08_),
    .Z(_00_)
  );
  BUF_X1 _59_ (
    .A(din[1]),
    .Z(_17_)
  );
  BUF_X1 _60_ (
    .A(dout[2]),
    .Z(_26_)
  );
  BUF_X1 _61_ (
    .A(_09_),
    .Z(_01_)
  );
  BUF_X1 _62_ (
    .A(din[2]),
    .Z(_18_)
  );
  BUF_X1 _63_ (
    .A(dout[3]),
    .Z(_27_)
  );
  BUF_X1 _64_ (
    .A(_10_),
    .Z(_02_)
  );
  BUF_X1 _65_ (
    .A(din[3]),
    .Z(_19_)
  );
  BUF_X1 _66_ (
    .A(dout[4]),
    .Z(_28_)
  );
  BUF_X1 _67_ (
    .A(_11_),
    .Z(_03_)
  );
  BUF_X1 _68_ (
    .A(din[4]),
    .Z(_20_)
  );
  BUF_X1 _69_ (
    .A(dout[5]),
    .Z(_29_)
  );
  BUF_X1 _70_ (
    .A(_12_),
    .Z(_04_)
  );
  BUF_X1 _71_ (
    .A(din[5]),
    .Z(_21_)
  );
  BUF_X1 _72_ (
    .A(dout[6]),
    .Z(_30_)
  );
  BUF_X1 _73_ (
    .A(_13_),
    .Z(_05_)
  );
  BUF_X1 _74_ (
    .A(din[6]),
    .Z(_22_)
  );
  BUF_X1 _75_ (
    .A(dout[7]),
    .Z(_31_)
  );
  BUF_X1 _76_ (
    .A(_14_),
    .Z(_06_)
  );
  BUF_X1 _77_ (
    .A(dout[0]),
    .Z(_24_)
  );
  BUF_X1 _78_ (
    .A(din[7]),
    .Z(_23_)
  );
  BUF_X1 _79_ (
    .A(_15_),
    .Z(_07_)
  );
  DFF_X1 _80_ (
    .CK(clk),
    .D(_00_),
    .Q(dout[0]),
    .QN(_36_)
  );
  DFF_X1 _81_ (
    .CK(clk),
    .D(_01_),
    .Q(dout[1]),
    .QN(_37_)
  );
  DFF_X1 _82_ (
    .CK(clk),
    .D(_02_),
    .Q(dout[2]),
    .QN(_38_)
  );
  DFF_X1 _83_ (
    .CK(clk),
    .D(_03_),
    .Q(dout[3]),
    .QN(_39_)
  );
  DFF_X1 _84_ (
    .CK(clk),
    .D(_04_),
    .Q(dout[4]),
    .QN(_40_)
  );
  DFF_X1 _85_ (
    .CK(clk),
    .D(_05_),
    .Q(dout[5]),
    .QN(_41_)
  );
  DFF_X1 _86_ (
    .CK(clk),
    .D(_06_),
    .Q(dout[6]),
    .QN(_42_)
  );
  DFF_X1 _87_ (
    .CK(clk),
    .D(_07_),
    .Q(dout[7]),
    .QN(_43_)
  );
endmodule

module segment_hex(bcd, seg_display);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  input [3:0] bcd;
  output [7:0] seg_display;
  INV_X16 _39_ (
    .A(_02_),
    .ZN(_04_)
  );
  NOR2_X4 _40_ (
    .A1(_04_),
    .A2(_03_),
    .ZN(_05_)
  );
  AND2_X4 _41_ (
    .A1(_01_),
    .A2(_00_),
    .ZN(_06_)
  );
  AND2_X4 _42_ (
    .A1(_05_),
    .A2(_06_),
    .ZN(_07_)
  );
  NOR2_X4 _43_ (
    .A1(_03_),
    .A2(_02_),
    .ZN(_08_)
  );
  INV_X16 _44_ (
    .A(_00_),
    .ZN(_09_)
  );
  NOR2_X2 _45_ (
    .A1(_09_),
    .A2(_01_),
    .ZN(_10_)
  );
  AOI21_X4 _46_ (
    .A(_07_),
    .B1(_08_),
    .B2(_10_),
    .ZN(_11_)
  );
  INV_X1 _47_ (
    .A(_05_),
    .ZN(_12_)
  );
  INV_X1 _48_ (
    .A(_03_),
    .ZN(_13_)
  );
  NOR2_X1 _49_ (
    .A1(_13_),
    .A2(_02_),
    .ZN(_14_)
  );
  INV_X1 _50_ (
    .A(_14_),
    .ZN(_15_)
  );
  NOR2_X1 _51_ (
    .A1(_01_),
    .A2(_00_),
    .ZN(_16_)
  );
  NAND3_X1 _52_ (
    .A1(_12_),
    .A2(_15_),
    .A3(_16_),
    .ZN(_17_)
  );
  NAND2_X1 _53_ (
    .A1(_11_),
    .A2(_17_),
    .ZN(_31_)
  );
  AND2_X2 _54_ (
    .A1(_03_),
    .A2(_02_),
    .ZN(_18_)
  );
  NAND2_X1 _55_ (
    .A1(_10_),
    .A2(_18_),
    .ZN(_19_)
  );
  INV_X1 _56_ (
    .A(_08_),
    .ZN(_20_)
  );
  INV_X1 _57_ (
    .A(_06_),
    .ZN(_21_)
  );
  OAI221_X1 _58_ (
    .A(_19_),
    .B1(_20_),
    .B2(_16_),
    .C1(_12_),
    .C2(_21_),
    .ZN(_32_)
  );
  INV_X32 _59_ (
    .A(_01_),
    .ZN(_22_)
  );
  OAI211_X2 _60_ (
    .A(_13_),
    .B(_02_),
    .C1(_22_),
    .C2(_00_),
    .ZN(_23_)
  );
  NAND4_X1 _61_ (
    .A1(_04_),
    .A2(_22_),
    .A3(_03_),
    .A4(_00_),
    .ZN(_24_)
  );
  OAI211_X2 _62_ (
    .A(_23_),
    .B(_24_),
    .C1(_20_),
    .C2(_09_),
    .ZN(_33_)
  );
  AOI22_X1 _63_ (
    .A1(_05_),
    .A2(_16_),
    .B1(_06_),
    .B2(_18_),
    .ZN(_25_)
  );
  NOR2_X1 _64_ (
    .A1(_22_),
    .A2(_00_),
    .ZN(_26_)
  );
  INV_X1 _65_ (
    .A(_26_),
    .ZN(_27_)
  );
  OAI211_X2 _66_ (
    .A(_11_),
    .B(_25_),
    .C1(_15_),
    .C2(_27_),
    .ZN(_34_)
  );
  OAI21_X1 _67_ (
    .A(_18_),
    .B1(_01_),
    .B2(_09_),
    .ZN(_28_)
  );
  OAI21_X1 _68_ (
    .A(_28_),
    .B1(_27_),
    .B2(_20_),
    .ZN(_35_)
  );
  OAI21_X1 _69_ (
    .A(_05_),
    .B1(_10_),
    .B2(_26_),
    .ZN(_29_)
  );
  OAI211_X2 _70_ (
    .A(_29_),
    .B(_28_),
    .C1(_21_),
    .C2(_15_),
    .ZN(_36_)
  );
  AOI22_X1 _71_ (
    .A1(_08_),
    .A2(_10_),
    .B1(_05_),
    .B2(_16_),
    .ZN(_30_)
  );
  OAI211_X2 _72_ (
    .A(_30_),
    .B(_19_),
    .C1(_21_),
    .C2(_15_),
    .ZN(_37_)
  );
  LOGIC1_X1 _73_ (
    .Z(_38_)
  );
  BUF_X1 _74_ (
    .A(_38_),
    .Z(seg_display[0])
  );
  BUF_X1 _75_ (
    .A(bcd[3]),
    .Z(_03_)
  );
  BUF_X1 _76_ (
    .A(bcd[2]),
    .Z(_02_)
  );
  BUF_X1 _77_ (
    .A(bcd[1]),
    .Z(_01_)
  );
  BUF_X1 _78_ (
    .A(bcd[0]),
    .Z(_00_)
  );
  BUF_X1 _79_ (
    .A(_31_),
    .Z(seg_display[1])
  );
  BUF_X1 _80_ (
    .A(_32_),
    .Z(seg_display[2])
  );
  BUF_X1 _81_ (
    .A(_33_),
    .Z(seg_display[3])
  );
  BUF_X1 _82_ (
    .A(_34_),
    .Z(seg_display[4])
  );
  BUF_X1 _83_ (
    .A(_35_),
    .Z(seg_display[5])
  );
  BUF_X1 _84_ (
    .A(_36_),
    .Z(seg_display[6])
  );
  BUF_X1 _85_ (
    .A(_37_),
    .Z(seg_display[7])
  );
endmodule

module top(clk, rst_n, data, segment_dis);
  wire \bcd[0] ;
  wire \bcd[1] ;
  wire \bcd[2] ;
  wire \bcd[3] ;
  wire \bcd[4] ;
  wire \bcd[5] ;
  wire \bcd[6] ;
  wire \bcd[7] ;
  input clk;
  input [7:0] data;
  input rst_n;
  output [15:0] segment_dis;
  lfsr u_lfsr (
    .clk(clk),
    .din(data),
    .dout({ \bcd[7] , \bcd[6] , \bcd[5] , \bcd[4] , \bcd[3] , \bcd[2] , \bcd[1] , \bcd[0]  }),
    .rst_n(rst_n)
  );
  segment_hex u_seg1 (
    .bcd({ \bcd[3] , \bcd[2] , \bcd[1] , \bcd[0]  }),
    .seg_display(segment_dis[7:0])
  );
  segment_hex u_seg2 (
    .bcd({ \bcd[7] , \bcd[6] , \bcd[5] , \bcd[4]  }),
    .seg_display(segment_dis[15:8])
  );
endmodule
